### ISSUE TITLE
The last change broke make-namespace, because ituses ,@ incorrectly

### ISSUE THREAD

**Issue by Yehouda** [eadmund/cl-sxml#1]
The last change to make-namespace broke it, because it uses ,@ incorrectly. Now the test produces 
 (*namespaces* (|http://www.w3.org/1999/xhtml| "http://www.w3.org/1999/xhtml" . \h))

instead of:

 (*namespaces* (|http://www.w3.org/1999/xhtml| "http://www.w3.org/1999/xhtml"  \h))

To make it work, the last form of   make-namespace need to change to: 

,@(when local-name
           `(,(intern local-name package)))

**Comment by eadmund** [comment]
Fixed.  Feel free to submit a PR in the future!
